### ISSUE TITLE
All sensors show "0"

### ISSUE THREAD

**Issue by pglizniewicz** [wiiznokes/fan-control#11]
I've built the project, had to add `export CFLAGS=-fPIC` or it would not link with libsensors. The result is:

![fan-control](https://github.com/wiiznokes/fan-control/assets/4559130/99e8b4d3-6e89-4c77-8763-92c55d151124)

The system is Fedora 39, running on an ASUS Rampage IV Formula motherboard.

sensors returns:
```
nct6776-isa-0290
Adapter: ISA adapter
Vcore:           1.04 V  (min =  +0.00 V, max =  +1.74 V)
in1:             1.01 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
AVCC:            3.33 V  (min =  +2.98 V, max =  +3.63 V)
+3.3V:           3.31 V  (min =  +2.98 V, max =  +3.63 V)
in4:           1000.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
in5:             2.04 V  (min =  +0.00 V, max =  +0.00 V)  ALARM
in6:           776.00 mV (min =  +0.00 V, max =  +0.00 V)  ALARM
3VSB:            3.41 V  (min =  +2.98 V, max =  +3.63 V)
Vbat:            3.36 V  (min =  +2.70 V, max =  +3.63 V)
fan1:           694 RPM  (min =    0 RPM)
fan2:           400 RPM  (min =    0 RPM)
fan3:           448 RPM  (min =    0 RPM)
SYSTIN:         +34.0°C  (high =  +0.0°C, hyst =  +0.0°C)  ALARM  sensor = thermistor
CPUTIN:         +24.0°C  (high = +80.0°C, hyst = +75.0°C)  sensor = thermal diode
AUXTIN:         +38.0°C  (high = +80.0°C, hyst = +75.0°C)  sensor = thermistor
PECI Agent 0:   +30.0°C  (high = +80.0°C, hyst = +75.0°C)
                         (crit = +92.0°C)
PCH_CHIP_TEMP:   +0.0°C
PCH_CPU_TEMP:    +0.0°C
PCH_MCH_TEMP:    +0.0°C
intrusion0:    ALARM
intrusion1:    ALARM
beep_enable:   disabled

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +39.0°C  (high = +82.0°C, crit = +100.0°C)
Core 0:        +35.0°C  (high = +82.0°C, crit = +100.0°C)
Core 1:        +37.0°C  (high = +82.0°C, crit = +100.0°C)
Core 2:        +39.0°C  (high = +82.0°C, crit = +100.0°C)
Core 3:        +36.0°C  (high = +82.0°C, crit = +100.0°C)
```

**Comment by wiiznokes** [comment]
> I've built the project, had to add export CFLAGS=-fPIC or it would not link with libsensors

You should use the branch `libcosmic`, it contains a patch for it. However, last time i tried on Linux, i had some very weird panic (something related with ui rendering). Maybe its only the `libcosmic` branch, i'm curious about that.

The fact it shows 0 is actually normal, you have to select a behavior on the picklist of a control (the left column, where there is None).

But rn, you don't have any behaviors, you currently need to create them with a config file, you can copy past one of my test configs: https://github.com/wiiznokes/fan-control/tree/main/.config in ~/.config/fan-control/

don't forget to set the config name in the setting file.

When a sensor is not used in the config, e.i., it's value will not impact the % of the control, his value is not updated. I plan to make a mode more optimized for the UI in the future.

Also, note that i don't think i currently implemented the code to set the value of a control on Linux, i think it will only print a message in the console.

**Comment by pglizniewicz** [comment]
OK, I've rebuilt it and now it shows me a window without decorations and nothing is clickable. It also takes 2 minutes to start the executable (time since `Running `target/release/fan-control` is printed to the moment a window appears). I'm running a KDE Plasma 5 session on Wayland. The graphics is nVidia GTX1080 with nvidia drivers if that matters.

![image](https://github.com/wiiznokes/fan-control/assets/4559130/88a411f3-ed8d-4679-abad-45745b6a0eea)

**Comment by pglizniewicz** [comment]
I won't have access to the machine I've previously tested for another two weeks, checked it briefly on my ThinkPad X13 G3 AMD laptop on Fedora 40 with KDE Plasma 6 and it works.
