### ISSUE TITLE
Can't start on linux

### ISSUE THREAD

**Issue by IcHiAT** [wiiznokes/fan-control#116]
chris@ChrisMint:~$ flatpak run io.github.wiiznokes.fan-control
thread 'main' panicked at /run/build/fan-control/cargo/vendor/iced_tiny_skia/src/window/compositor.rs:56:10:
Create softbuffer surface for window: PlatformError(Some("Visual 0x80 does not use softbuffer's pixel format and is unsupported"), None)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[ERROR hardware::linux] can't set auto to a pwm sensor when quitting: sensors_set_value() failed: [4] Kernel interface error
[ERROR hardware::linux] can't set auto to a pwm sensor when quitting: sensors_set_value() failed: [4] Kernel interface error
[ERROR hardware::linux] can't set auto to a pwm sensor when quitting: sensors_set_value() failed: [4] Kernel interface error
[ERROR hardware::linux] can't set auto to a pwm sensor when quitting: sensors_set_value() failed: [4] Kernel interface error
[ERROR hardware::linux] can't set auto to a pwm sensor when quitting: sensors_set_value() failed: [4] Kernel interface error
[ERROR hardware::linux] can't set auto to a pwm sensor when quitting: sensors_set_value() failed: [4] Kernel interface error
[ERROR hardware::linux] can't set auto to a pwm sensor when quitting: sensors_set_value() failed: [4] Kernel interface error
[ERROR hardware::linux] can't set auto to a pwm sensor when quitting: sensors_set_value() failed: [4] Kernel interface error
[ERROR hardware::linux] can't set auto to a pwm sensor when quitting: sensors_set_value() failed: [4] Kernel interface error

**Comment by wiiznokes** [comment]
I just pushed an update on flathub that should solve the crash. anyway, this issue has already been reported in #98.

The others errors are because you missing the udev rules. See the installation section on the readme for more information on it.
