### ISSUE TITLE
UI feature compilation

### ISSUE THREAD

**Issue by Xavantex** [wiiznokes/fan-control#138]
#### Use Case
I noticed as it is now the compiled binary needs x11 library. Myself I want to run it on a headless server to monitor my hdd devices primarily, so I don't need x11 libraries.

Is this something that would be wanted as either maybe a branch or in main repo.
I implemented a "quickfix" configuring out the UI if specified at compile time.

I tried to seperate the localization as it also seems unecessary witout a gui.
But it seems a bit too integrated to fix without major changes at the moment.
I could look into it if wider seperation is something that is wanted.

#### Who Benefits From The Change(s) ?
Those who don't have/want x11 common libraries, and don't need the UI.

**Comment by wiiznokes** [comment]
Yes, you can make a pull request with an ui feature.

> Myself I want to run it on a headless server to monitor my hdd devices primarily

An head less fan-control will only be useful to controls fans currently. You will not be able to monitor anything

**Comment by wiiznokes** [comment]
> I tried to seperate the localization as it also seems unecessary witout a gui.
But it seems a bit too integrated to fix without major changes at the moment.

It might make sense to do it in the future, because the localization crates are kinda heavy.
