### ISSUE TITLE
Padding off - top bar buttons

### ISSUE THREAD

**Issue by Jopp-gh** [wiiznokes/fan-control#149]
#### Bug Description
the padding of icons in the top bar is a little bit off. Minor, but still a bug.

#### Expected Result
padding of icon placement corrected

#### Steps to Reproduce
check the top bar, please see attachment
![Fan C ](https://github.com/user-attachments/assets/3639af8a-e6f7-423a-8d55-3206a63f6cdb)

#### Operating system
Linux Mint, Virginia

#### fan-control version
2024.6

**Comment by wiiznokes** [comment]
It must be fixed on master, but I need to make a new release

**Comment by wiiznokes** [comment]
should be fixed, you can re open if needed

**Comment by wiiznokes** [comment]
Yeah, should be fixed in the next release
