### ISSUE TITLE
Program running but not opening window or shown in tray icon

### ISSUE THREAD

**Issue by Camadams1179** [wiiznokes/fan-control#155]
Note: Feel free to fill only the sections that feels relevant to you

#### Bug Description
Updated to current version, Fan control doesn't show in tray like usual. Shows in task manager as running. 
#### Possible Additional Information (optional)
Troubleshooting: 
Reinstalled Application
Updated Windows 10
Downgraded and successfully works without issue
Ran in Compatibility with Windows 8
Run with Admin Permissions
#### Operating system
Windows 10 x64
#### fan-control version
2024.7.30
#### Logs

On linux, run `flatpak run io.github.wiiznokes.fan-control` in a terminal.

**Comment by wiiznokes** [comment]
Have you managed to fix it?
