### ISSUE TITLE
failed build on arch linux

### ISSUE THREAD

**Issue by blind-confused** [wiiznokes/fan-control#88]
for some reason, it didn't work... 
I ran the following commands:
```
sudo pacman -S lm-sensors
sudo sensors-detect
```
and saved the output, then installed rust using the official website instructions (which means using the following command): `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
then I ran: 
```
cargo install just
sudo pacman -S make bison flex clang --confirm
```
but when I ran `just libsensors`, it just said `error: No justfile found`
same thing happened after I tried uninstalling just and rust, and then reinstalling them, but from arch repositories. Honestly not sure what's wrong...

**Comment by wiiznokes** [comment]
No worries, we all been there. I updated the doc to make it even clear for beginners: https://github.com/wiiznokes/fan-control/blob/main/BUILD.md

**Comment by wiiznokes** [comment]
Notice you will need to run in sudo to be able to modify the value of PWM sensor (fans).
So `sudo ./target/release/fan-control`.

After building the app obviously (cargo run --release or cargo build --release)

**Comment by wiiznokes** [comment]
Well, they can be one item per sensor, so you can create different behavior based on a specific sensor(CPU for example). If you don't want to go above 70°C, you could use the target behavior. Or the linear. Personnaly, I'm only using this app to game and put all my fan at full speed

**Comment by wiiznokes** [comment]
Hum, from what I see you have no pwm sensor detected. The only solution is to run sensor-detect and answer yes every time, but i think you already did that so probably you're fan can't be controlled (it's frequent on laptop).

For the icons being black, maybe it's a bug with vulkan, you try to set `ICED_BACKEND=tiny-skia` before running.

As for the error message, this is weird, it should never happened on Linux. Maybe retry with sudo

**Comment by wiiznokes** [comment]
> well... sudo: ./target/release/fan-control: command not found

You must be in the fan-control folder for this.

> got it, I guess I will cry :,

Yeah this is sad, but maybe is could be improve, will see

**Comment by wiiznokes** [comment]
Closing because the icons now should work with flatpak
